on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set GOPATH
      run: go env -w GOPATH=$HOME/go
    - name: Set GOBIN
      run: mkdir bin && export GOBIN=$GOPATH/bin
    - name: go get
      run: go get ./...
    - name: go build
      run: go build
    - name: Test
      run: go test ./...